### ISSUE TITLE
Syntax issue with wiki page

### ISSUE THREAD

**Issue by anoobbava** [amitree/delayed_job_recurring#24]
Hi,
```ruby
# lib/tasks/recurring_jobs.rake

namespace :recurring
  task init: :environment do
    MyTask.schedule!
    MyOtherTask.schedule!

    if Rails.env.production?
      MyProductionOnlyTask.schedule!
    end
  end
end
```
Causes issue 
```
rake aborted!
SyntaxError: /home/anoobbava/ror/approval_system/lib/tasks/recurring_jobs.rake:7: syntax error, unexpected keyword_end, expecting end-of-input
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:648:in `block in run_tasks_blocks'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:648:in `each'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:648:in `run_tasks_blocks'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application.rb:440:in `run_tasks_blocks'
/home/anoobbava/ror/approval_system/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:457:in `load_tasks'
/home/anoobbava/ror/approval_system/Rakefile:6:in `<top (required)>'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/anoobbava/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/anoobbava/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
/home/anoobbava/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
/home/anoobbava/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/anoobbava/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

```

it is syntax issue and it is fixed with #23  , Please merge

**Comment by anoobbava** [comment]
this issue is fixed ,So issue is closed
