### ISSUE TITLE
How to access the 'schedule_options' when I load the YAML?

### ISSUE THREAD

**Issue by laphlaw** [amitree/delayed_job_recurring#29]
2.3.4 :022 > y=YAML::load(Delayed::Job.last.last.handler)
 => #<CheckExercise:0x007f8f9205c8b8 @schedule_options={:run_at=>[Sat, 09 Feb 2019 21:30:00 PST -08:00, Sat, 09 Feb 2019 23:57:00 PST -08:00], :timezone=>"US/Pacific", :run_interval=>{:value=>86400, :parts=>[[:days, 1]]}, :priority=>nil, :queue=>"slow-jobs"}> 

2.3.4 :025 > y[:schedule_options]
NoMethodError: undefined method `[]' for #<CheckExercise:0x007f8f9205c8b8>
	from (irb):25
	from /Users/neil/.rvm/gems/ruby-2.3.4@rails-omniauth/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
	from /Users/neil/.rvm/gems/ruby-2.3.4@rails-omniauth/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/neil/.rvm/gems/ruby-2.3.4@rails-omniauth/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/neil/.rvm/gems/ruby-2.3.4@rails-omniauth/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/neil/.rvm/gems/ruby-2.3.4@rails-omniauth/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by anoobbava** [comment]
Please provide steps to reproduce this
